Repository sepandhaghighi/mytimer, pull requests merged in 2023-07, with the labels that each got.

#32 Release instructions
  otherfiles/RELEASE.md
Labels: documentation

#33 Version 0.6
  CHANGELOG.md
  README.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#34 Tone
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  TONES.md
  mytimer/__main__.py
  mytimer/functions.py
  mytimer/params.py
  mytimer/sounds/10.wav
  mytimer/sounds/11.wav
  mytimer/sounds/3.wav
  mytimer/sounds/4.wav
  mytimer/sounds/5.wav
  mytimer/sounds/6.wav
  mytimer/sounds/7.wav
  mytimer/sounds/8.wav
  mytimer/sounds/9.wav
Labels: enhancement

#35 Document update
  CHANGELOG.md
  FACES.md
  PROGRAMS.md
Labels: documentation

#36 Refactor
  CHANGELOG.md
  mytimer/functions.py
Labels: enhancement

#38 Version 0.7
  CHANGELOG.md
  README.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#40 Fix audio length
  AUTHORS.md
  CHANGELOG.md
  TONES.md
  mytimer/sounds/10.wav
  mytimer/sounds/11.wav
  mytimer/sounds/3.wav
  mytimer/sounds/4.wav
  mytimer/sounds/5.wav
  mytimer/sounds/6.wav
  mytimer/sounds/7.wav
  mytimer/sounds/8.wav
  mytimer/sounds/9.wav
Labels: bug
