Repository sepandhaghighi/mytimer, pull requests merged in 2023-10, with the labels that each got.

#56 Version 0.9
  CHANGELOG.md
  README.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#58 Program bug fix
  CHANGELOG.md
  mytimer/params.py
Labels: bug

#59 `--programs-list` argument added
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  mytimer/__main__.py
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement, new feature

#60 Add `--faces-list` flag
  .github/workflows/test.yml
  AUTHORS.md
  CHANGELOG.md
  README.md
  mytimer/__main__.py
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement, new feature

#63 Minor edits
  AUTHORS.md
  mytimer/functions.py
Labels: enhancement

#64 Vertical & Horizontal Shift
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  mytimer/__main__.py
  mytimer/functions.py
  mytimer/params.py
  requirements.txt
Labels: enhancement
