Repository sepandhaghighi/mytimer, pull requests merged in 2023-11, with the labels that each got.

#65 `DEFAULT_PARAMS` added
  CHANGELOG.md
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement

#68 Minor edits
  .github/workflows/test.yml
  README.md
  mytimer/params.py
Labels: enhancement

#69 Version 1.0
  CHANGELOG.md
  README.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#70 New on exit message
  CHANGELOG.md
  mytimer/__main__.py
  mytimer/params.py
Labels: enhancement

#71 Python 3.12
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  setup.py
Labels: test
