Repository sepandhaghighi/mytimer, pull requests merged in 2024-08, with the labels that each got.

#103 New programs
  CHANGELOG.md
  PROGRAMS.md
  README.md
  mytimer/params.py
Labels: new program

#104 Programs message
  CHANGELOG.md
  mytimer/params.py
Labels: enhancement

#105 Version 1.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#107 New programs
  CHANGELOG.md
  PROGRAMS.md
  README.md
  mytimer/params.py
Labels: new program

#108 `--set-on` Mode
  CHANGELOG.md
  README.md
  mytimer/__main__.py
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement, new feature

#109 Default mode
  CHANGELOG.md
  README.md
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement

#110 `white-tea` program update
  CHANGELOG.md
  PROGRAMS.md
  mytimer/params.py
Labels: bug, minor

#111 Version 1.6
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#112 ci : fix typo
  .github/ISSUE_TEMPLATE/feature_request.yml
  AUTHORS.md
Labels: documentation
