Repository sepandhaghighi/mytimer, pull requests merged in 2024-10, with the labels that each got.

#116 New tones
  CHANGELOG.md
  mytimer/params.py
  mytimer/sounds/15.wav
  mytimer/sounds/16.wav
  mytimer/sounds/17.wav
  mytimer/sounds/18.wav
  mytimer/sounds/19.wav
  mytimer/sounds/20.wav
Labels: enhancement, new tone

#117 Version 1.7
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#118 Face random mode
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  mytimer/__main__.py
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement

#119 Tone random mode
  CHANGELOG.md
  README.md
  mytimer/__main__.py
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement

#120 New tones
  CHANGELOG.md
  mytimer/params.py
  mytimer/sounds/21.wav
  mytimer/sounds/22.wav
  mytimer/sounds/23.wav
  mytimer/sounds/24.wav
  mytimer/sounds/25.wav
Labels: new tone

#121 Python 3.13
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/test.yml
  CHANGELOG.md
  setup.py
Labels: test

#122 Version 1.8
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#123 Add/limit gh action run
  .github/workflows/test.yml
  CHANGELOG.md
Labels: test
