Repository sepandhaghighi/mytimer, pull requests merged in 2025-01, with the labels that each got.

#134 Coffee break
  CHANGELOG.md
  PROGRAMS.md
  mytimer/params.py
Labels: new program

#136 `README.md` update
  CHANGELOG.md
  README.md
Labels: documentation

#139 Clock/Date
  CHANGELOG.md
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement

#140 `print_date_time` Function Added
  mytimer/functions.py
Labels: refactoring

#141 `--hide-datetime`
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  mytimer/__main__.py
  mytimer/functions.py
  mytimer/params.py
Labels: enhancement

#142 Meditation
  CHANGELOG.md
  PROGRAMS.md
  mytimer/params.py
Labels: new program

#143 Version 2.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mytimer/params.py
  otherfiles/version_check.py
  setup.py
Labels: release
